In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

In [2]:
data = {
    "Student": ["Aman", "Riya", "Karan", "Simran", "Rahul", "Neha", "Arjun", "Pooja"],
    "Department": ["CSE", "CSE", "ECE", "ECE", "CSE", "ECE", "CSE", "ECE"],
    "Math_Marks": [78, 92, 67, 85, 74, 88, 81, 70],
    "Python_Marks": [82, 95, 72, 80, 69, 91, 86, 75],
    "Attendance": [85, 96, 75, 90, 70, 94, 88, 78],
    "Result": ["Pass", "Pass", "Pass", "Pass", "Pass", "Pass", "Pass", "Pass"]
}

In [3]:
df = pd.DataFrame(data)

In [4]:
df

  Student Department  Math_Marks  Python_Marks  Attendance Result
0    Aman        CSE          78            82          85   Pass
1    Riya        CSE          92            95          96   Pass
2   Karan        ECE          67            72          75   Pass
3  Simran        ECE          85            80          90   Pass
4   Rahul        CSE          74            69          70   Pass
5    Neha        ECE          88            91          94   Pass
6   Arjun        CSE          81            86          88   Pass
7   Pooja        ECE          70            75          78   Pass

In [6]:
df.head(3)

  Student Department  Math_Marks  Python_Marks  Attendance Result
0    Aman        CSE          78            82          85   Pass
1    Riya        CSE          92            95          96   Pass
2   Karan        ECE          67            72          75   Pass

In [11]:
df.tail()

  Student Department  Math_Marks  Python_Marks  Attendance Result
3  Simran        ECE          85            80          90   Pass
4   Rahul        CSE          74            69          70   Pass
5    Neha        ECE          88            91          94   Pass
6   Arjun        CSE          81            86          88   Pass
7   Pooja        ECE          70            75          78   Pass

In [9]:
df.shape

(8, 6)

In [10]:
df.columns

Index(['Student', 'Department', 'Math_Marks', 'Python_Marks', 'Attendance',
       'Result'],
      dtype='str')

In [12]:
df.columns.tolist()

['Student', 'Department', 'Math_Marks', 'Python_Marks', 'Attendance', 'Result']

In [13]:
df.describe(include = 'all')

       Student Department  Math_Marks  Python_Marks  Attendance Result
count        8          8    8.000000      8.000000    8.000000      8
unique       8          2         NaN           NaN         NaN      1
top       Aman        CSE         NaN           NaN         NaN   Pass
freq         1          4         NaN           NaN         NaN      8
mean       NaN        NaN   79.375000     81.250000   84.500000    NaN
std        NaN        NaN    8.782084      9.130013    9.319718    NaN
min        NaN        NaN   67.000000     69.000000   70.000000    NaN
25%        NaN        NaN   73.000000     74.250000   77.250000    NaN
50%        NaN        NaN   79.500000     81.000000   86.500000    NaN
75%        NaN        NaN   85.750000     87.250000   91.000000    NaN
max        NaN        NaN   92.000000     95.000000   96.000000    NaN

In [14]:
df.describe

<bound method NDFrame.describe of   Student Department  Math_Marks  Python_Marks  Attendance Result
0    Aman        CSE          78            82          85   Pass
1    Riya        CSE          92            95          96   Pass
2   Karan        ECE          67            72          75   Pass
3  Simran        ECE          85            80          90   Pass
4   Rahul        CSE          74            69          70   Pass
5    Neha        ECE          88            91          94   Pass
6   Arjun        CSE          81            86          88   Pass
7   Pooja        ECE          70            75          78   Pass>

In [15]:
df["Math_Marks"]

0    78
1    92
2    67
3    85
4    74
5    88
6    81
7    70
Name: Math_Marks, dtype: int64

In [16]:
df[["Student", "Python_Marks"]]

  Student  Python_Marks
0    Aman            82
1    Riya            95
2   Karan            72
3  Simran            80
4   Rahul            69
5    Neha            91
6   Arjun            86
7   Pooja            75

In [17]:
df["Average_Marks"] = ( df["Math_Marks"] + df["Python_Marks"] ) / 2

In [18]:
df

,Student,Department,Math_Marks,Python_Marks,Attendance,Result,Average_Marks
0,Aman,CSE,78,82,85,Pass,80.0
1,Riya,CSE,92,95,96,Pass,93.5
2,Karan,ECE,67,72,75,Pass,69.5
3,Simran,ECE,85,80,90,Pass,82.5
4,Rahul,CSE,74,69,70,Pass,71.5
5,Neha,ECE,88,91,94,Pass,89.5
6,Arjun,CSE,81,86,88,Pass,83.5
7,Pooja,ECE,70,75,78,Pass,72.5